function Input = input(param,tau0,ein)

Input  = sqrt(ein/(2*tau0))*(sech(-param+3.52))...
        +sqrt(ein/(2*tau0))*(sech(-param+10.57))...
        +sqrt(ein/(2*tau0))*(sech(-param+17.65))...
        +sqrt(ein/(2*tau0))*(sech(-param+45.83));

